Repository FriesischScott/UncertaintyQuantification.jl, pull requests merged in 2024-10, with the labels that each got.

#223 Fix interval propagation for degenerate intervals
  demo/reliability/linesampling.jl
  src/inputs/imprecise/interval.jl
  src/inputs/imprecise/p-box.jl
  src/models/imprecise/propagation.jl
  src/reliability/probabilityoffailure.jl
  src/simulations/linesampling.jl
  test/inputs/imprecise/p-box.jl
  test/reliability/probabilityoffailure.jl
Labels: bug, enhancement

#206 Add evaluation of support for ProbabilityBoxes with Uniform
  src/inputs/imprecise/p-box.jl
  test/inputs/imprecise/p-box.jl
Labels: bug

#225 Add parallelisation section to docs
  demo/external/01-opensees.jl
  demo/external/02-opensees-parallel.jl
  demo/reliability/supported-beam-opensees.jl
  docs/literate/bayesianupdating/inverse-eigenvalue.jl
  docs/literate/external/01-opensees.jl
  docs/literate/external/02-opensees-parallel.jl
  docs/literate/metamodels/responsesurface.jl
  docs/literateDocs.jl
  docs/make.jl
  docs/src/api/models.md
  docs/src/manual/gettingstarted.md
  docs/src/manual/hpc.md
  docs/src/manual/parallelisation.md
  src/UncertaintyQuantification.jl
  src/models/model.jl
  src/models/responsesurface.jl
Labels: documentation

#231 Documentation maintenance
  docs/literate/bayesianupdating/inverse-eigenvalue.jl
  docs/literate/metamodels/responsesurface.jl
  docs/make.jl
  docs/references.bib
  docs/src/api/inputs.md
  docs/src/api/simulations.md
  docs/src/benchmarks/subset.md
  docs/src/manual/bayesianupdating.md
  docs/src/manual/gettingstarted.md
  docs/src/manual/introduction.md
  docs/src/manual/reliability.md
  docs/src/manual/simulations.md
  src/inputs/imprecise/p-box.jl
  src/inputs/inputs.jl
  src/inputs/randomvariables/randomvariable.jl
  src/models/model.jl
  src/models/responsesurface.jl
  src/models/slicingmodel.jl
  src/modelupdating/bayesianupdating.jl
  src/simulations/subset.jl
Labels: documentation
