Repository FriesischScott/UncertaintyQuantification.jl, pull requests merged in 2024-09, with the labels that each got.

#199 Improve Bayesian updating tests
  test/modelupdating/bayesianupdating.jl
Labels: enhancement, housekeeping

#207 Pass slurm options as dict
  demo/hpc/slurm-openmc.jl
  docs/literate/hpc/slurm-openmc.jl
  scripts/updateDemos.ps1
  scripts/updateDemos.sh
  src/hpc/slurm.jl
  test/hpc/slurm.jl
Labels: enhancement

#202 Add Advanced Line Sampling
  demo/reliability/linesampling.jl
  src/UncertaintyQuantification.jl
  src/reliability/probabilityoffailure.jl
  src/simulations/linesampling.jl
  test/reliability/probabilityoffailure.jl
Labels: feature

#180 Stochastic dynamics framework
  Project.toml
  demo/dynamics/cantilever-column.jl
  demo/dynamics/single-degree-of-freedom.jl
  demo/models/opensees-cantilever-column/cantilever-column.tcl
  demo/models/opensees-cantilever-column/ground-motion.dat
  demo/reliability/supported-beam-opensees.jl
  docs/references.bib
  docs/src/manual/dynamics.md
  src/UncertaintyQuantification.jl
  src/dynamics/psd.jl
  src/inputs/inputs.jl
  src/inputs/stochasticprocesses/models.jl
  src/inputs/stochasticprocesses/spectralrepresentation.jl
  src/models/external/externalmodel.jl
  src/util/fourier-transform.jl
  test/dynamics/psd.jl
  test/inputs/stochasticprocesses/spectralrepresentation.jl
  test/util/fourier-transform.jl
Labels: enhancement

#219 Update reliability documentation
  demo/reliability/linesampling.jl
  demo/reliability/quadratic-performance.jl
  docs/references.bib
  docs/src/manual/reliability.md
Labels: documentation
