Repository FriesischScott/UncertaintyQuantification.jl, pull requests merged in 2024-07, with the labels that each got.

#175 Add Subset benchmark
  docs/make.jl
  docs/src/assets/scripts/subset-benchmark-base.jl
  docs/src/assets/scripts/subset-benchmark-dimensions.jl
  docs/src/assets/scripts/subset-benchmark-pf.jl
  docs/src/assets/scripts/subset-benchmark-samples.jl
  docs/src/assets/subset-dimensions.svg
  docs/src/assets/subset-pf.svg
  docs/src/assets/subset-samples.svg
  docs/src/benchmarks/subset.md
Labels: documentation

#146 Imprecise probabilities
  Project.toml
  demo/reliability/alvarez-2d-with-pboxes.jl
  demo/reliability/front_axle-with-pboxes.jl
  src/UncertaintyQuantification.jl
  src/inputs/imprecise/interval.jl
  src/inputs/imprecise/p-box.jl
  src/inputs/inputs.jl
  src/models/externalmodel.jl
  src/models/imprecise/propagation.jl
  src/models/slicingmodel.jl
  src/reliability/form.jl
  src/reliability/probabilityoffailure.jl
  src/reliability/probabilityoffailure_imprecise.jl
  src/simulations/doe.jl
  src/simulations/importancesampling.jl
  src/simulations/linesampling.jl
  src/simulations/montecarlo.jl
  src/simulations/subset.jl
  src/util/imprecise.jl
  test/inputs/imprecise/interval.jl
  test/inputs/imprecise/p-box.jl
  test/models/imprecise/propagation.jl
  test/reliability/probabilityoffailure.jl
  test/reliability/probabilityoffailure_imprecise.jl
  test/runtests.jl
Labels: feature

#178 Pass sns reference to gradient computation in standard normal space
  src/inputs/inputs.jl
  src/reliability/form.jl
  src/reliability/probabilityoffailure.jl
  src/sensitivity/gradient.jl
Labels: enhancement
